### ISSUE TITLE
Dropbox oAuthAuthorize URI incorrect

### ISSUE THREAD

**Issue by jacobbudin** [tijsverkoyen/Dropbox#1]
The oAuthAuthorize method should call the URI:
https://www.dropbox.com/0/oauth/authorize

Because Dropbox says so:
https://api.dropbox.com/developers/web_docs#authentication-for-web

My fix:

> ```
>   + const API_AUTH_URL = 'https://www.dropbox.com';
> 
>   oAuthAuthorize(
>     ...
>     // build url
>     - $url = self::API_URL .'/0/oauth/authorize?'. http_build_query($parameters);
>     + $url = self::API_AUTH_URL .'/0/oauth/authorize?'. http_build_query($parameters);
>     ...
> ```

Thanks for the hard work.

**Comment by tijsverkoyen** [comment]
Hi jacobbudin, it's fixed in https://github.com/tijsverkoyen/Dropbox/commit/5bbdc111290fb0da8e36d7175f0ba232354822ee
